version: '3.8'

services:

  web:
    image: palaeontologyhelsinki/cradle_of_humankind_staging
    restart: unless-stopped
    ports:
      - 8000:8000
    command: sh -c ./scripts/entrypoint.prod.sh
    volumes:
      - ./app/logs:/src/app/logs
      - static:/vol/web
    env_file:
      - ./.env
    container_name: coh_web_staging

  celery:
    image: palaeontologyhelsinki/cradle_of_humankind_staging
    restart: unless-stopped
    command: celery -A cradle_of_mankind worker -l INFO --concurrency=1
    volumes:
      - ./app/logs:/src/app/logs
      - static:/vol/web
    env_file:
      - ./.env
    depends_on:
      - redis
    container_name: coh_celery_staging

  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - "6379"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: coh_redis_staging

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/vol/web
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf:/etc/nginx/ssl/:ro
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - PMA_DOMAIN=${PMA_DOMAIN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - web
    container_name: coh_nginx_staging

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot/:rw
      - ./nginx/certbot/conf:/etc/letsencrypt/:rw
      - ./nginx/certbot/log:/var/log/:rw

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=${DB_HOST}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: coh_phpmyadmin_staging

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    container_name: coh_watchtower

volumes:
  static: null
