# Generated by Django 3.1.6 on 2021-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_contact_emails",
            field=models.BooleanField(default=False),
        ),
    ]
