# Generated by Django 3.1.6 on 2021-07-17 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_receive_contact_emails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="receive_contact_emails",
            new_name="receive_contact_email",
        ),
    ]
