[tool.black]
line-length = 79

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "cradle_of_mankind.settings"

[tool.pyright]
exclude = ["**/.venv"]
reportMissingImports = true
reportDuplicateImport = "warning"
