# Generated by Django 3.1.2 on 2021-01-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
