# Generated by Django 3.1.2 on 2021-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_auto_20210105_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
