# Generated by Django 3.1.2 on 2021-01-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0005_auto_20210105_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
