# Generated by Django 4.1.13 on 2024-12-11 19:02

import django.core.validators
from django.db import migrations, models
import zooniverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0010_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='file',
            field=models.FileField(upload_to=zooniverse.models.Import.name_based_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
