# Generated by Django 3.1.2 on 2021-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_masterfield_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfield',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
