# Generated by Django 3.1.6 on 2021-04-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_masterfield_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('prev_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('masterdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.masterdata')),
            ],
        ),
    ]
