# Generated by Django 3.1.6 on 2021-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20210420_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfield',
            name='display_order',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
