# Generated by Django 3.1.6 on 2021-07-20 08:22

from django.db import migrations, models
import django.db.models.deletion
import masterdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_source_masterdata_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterentity',
            old_name='source_entity',
            new_name='source_entities',
        ),
        migrations.RemoveField(
            model_name='editcomment',
            name='masterdata',
        ),
        migrations.RemoveField(
            model_name='masterdata',
            name='master_value',
        ),
        migrations.RemoveField(
            model_name='masterfield',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='sourcedata',
            name='source_value',
        ),
        migrations.AddField(
            model_name='editcomment',
            name='master_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.mastervalue'),
        ),
        migrations.AddField(
            model_name='masterentity',
            name='hidden_key',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='masterentity',
            name='master_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterfield',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastervalue',
            name='master_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.masterdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastervalue',
            name='source_data',
            field=models.ManyToManyField(to='masterdata.SourceData'),
        ),
        migrations.AddField(
            model_name='source',
            name='delimiter',
            field=models.CharField(default=';', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='source_file',
            field=models.FileField(default='1', upload_to=masterdata.models.Source.name_based_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceentity',
            name='source_key',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourcefield',
            name='is_primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcevalue',
            name='source_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_value', to='masterdata.sourcedata'),
            preserve_default=False,
        ),
    ]
