# Generated by Django 3.1.6 on 2021-06-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_source_masterdata_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfield',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
    ]
