# Generated by Django 3.1.6 on 2021-06-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_masterfield_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='master_value',
        ),
        migrations.AddField(
            model_name='masterdata',
            name='master_values',
            field=models.ManyToManyField(to='masterdata.MasterValue'),
        ),
    ]
