# Generated by Django 3.1.6 on 2021-06-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_auto_20210607_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterentity',
            name='master_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
