# Generated by Django 3.1.6 on 2021-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_mastervalue_source_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastervalue',
            name='source_data',
        ),
        migrations.AddField(
            model_name='mastervalue',
            name='source_data',
            field=models.ManyToManyField(to='masterdata.SourceData'),
        ),
    ]
