# Generated by Django 3.1.6 on 2021-07-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_auto_20210715_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefield',
            name='is_primary_key',
            field=models.BooleanField(default=False),
        ),
    ]
