# Generated by Django 3.1.6 on 2021-07-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0021_sourcefield_is_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_file',
            field=models.FileField(default=1, upload_to='source_files/<django.db.models.fields.CharField>'),
            preserve_default=False,
        ),
    ]
