# Generated by Django 3.1.6 on 2021-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0022_source_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delimiter',
            field=models.CharField(default=';', max_length=10),
            preserve_default=False,
        ),
    ]
