# Generated by Django 3.1.6 on 2021-07-16 05:57

from django.db import migrations, models
import masterdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0023_source_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_file',
            field=models.FileField(upload_to=masterdata.models.Source.name_based_upload),
        ),
    ]
