# Generated by Django 3.1.6 on 2021-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0025_sourceentity_source_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterentity',
            old_name='source_entity',
            new_name='source_entities',
        ),
    ]
