# Generated by Django 3.1.6 on 2021-07-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0026_auto_20210716_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editcomment',
            name='masterdata',
        ),
        migrations.RemoveField(
            model_name='masterdata',
            name='master_values',
        ),
        migrations.RemoveField(
            model_name='sourcedata',
            name='source_value',
        ),
        migrations.AddField(
            model_name='editcomment',
            name='master_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastervalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastervalue',
            name='master_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.masterdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcevalue',
            name='source_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.sourcedata'),
            preserve_default=False,
        ),
    ]
