# Generated by Django 3.1.2 on 2021-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20210319_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfield',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
