# Generated by Django 3.1.2 on 2021-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210319_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfield',
            name='sources',
            field=models.ManyToManyField(to='masterdata.Source'),
        ),
    ]
