# Generated by Django 3.1.6 on 2021-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20210420_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='master_created',
            field=models.BooleanField(default=False),
        ),
    ]
