# Generated by Django 3.1.6 on 2021-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_auto_20210720_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterentity',
            options={'ordering': ['master_key']},
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='source',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
    ]
