# Generated by Django 3.1.13 on 2021-12-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_auto_20210820_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfield',
            name='abbreviation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
