# Generated by Django 3.1.13 on 2021-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_masterfield_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfield',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
