# Generated by Django 4.0.2 on 2022-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20211221_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefield',
            name='num_of_mappings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
