# Generated by Django 4.0.4 on 2022-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_sourcefield_num_of_mappings_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfield',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Guest'), (2, 'Registered'), (3, 'Editor'), (4, 'Data Admin')], default=1),
        ),
    ]
