# Generated by Django 4.0.7 on 2022-09-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0021_masterfield_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editcomment',
            options={'default_related_name': 'edit_comments'},
        ),
        migrations.AlterModelOptions(
            name='masterdata',
            options={'default_related_name': 'master_datas'},
        ),
        migrations.AlterModelOptions(
            name='masterentity',
            options={'default_related_name': 'master_entities', 'ordering': ['master_key']},
        ),
        migrations.AlterModelOptions(
            name='masterfield',
            options={'default_related_name': 'master_fields', 'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='mastervalue',
            options={'default_related_name': 'master_values'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'default_related_name': 'sources'},
        ),
        migrations.AlterModelOptions(
            name='sourcedata',
            options={'default_related_name': 'source_datas'},
        ),
        migrations.AlterModelOptions(
            name='sourceentity',
            options={'default_related_name': 'source_entities'},
        ),
        migrations.AlterModelOptions(
            name='sourcefield',
            options={'default_related_name': 'source_fields', 'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='sourcevalue',
            options={'default_related_name': 'source_values'},
        ),
    ]
